AWSTemplateFormatVersion: 2010-09-09

Description: my s3

Resources:
  MyBucket:
    Type: AWS::S3::Bucket
    Properties: 
      BucketName: std21107

  S3ArnSSM:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Join [ '', [ td1 , -s3, -bucket ] ]
      Type: String
      Value: !GetAtt MyBucket.Arn